sonar.projectKey=https://sonarcloud.io/project/configuration?id=Abhayraj31_8.2C-DevSecOps
sonar.organization=Abhayraj31
sonar.host.url=https://sonarcloud.io
sonar.login=${8119a3732f3502b5d23c47f93c41aea785664e27}

sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
