sonar.projectKey=Abhayraj31_8.2C-DevSecOps
sonar.organization=Abhayraj31
sonar.host.url=https://sonarcloud.io

# Use the variable name SONAR_TOKEN. Jenkins will inject the actual secret.
sonar.login=${SONAR_TOKEN}

sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
